apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: books-api
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: apps/prod/books-api/charts/books-api
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    image:
      repository: acrdemoenterprise.azurecr.io/books-api
      tag: latest
    service:
      port: 8000
Mon Sep  1 20:44:19 UTC 2025
