apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orders-api
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/orders-api
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    image:
      repository: acrdemoenterprise.azurecr.io/orders-api
      tag: latest
    service:
      port: 5000